site_name: huangnan.lin DevZone
theme:
  name: material
  custom_dir: custom_theme
  features: 
    - navigation.instant
    - navigation.tabs
    - navigation.indexes
    - navigation.tabs.sticky
    - navigation.sections
    - header.autohide
  
markdown_extensions:
  - toc:
      permalink: true
      toc_depth: "2-4"
      slugify: !!python/name:pymdownx.slugs.uslugify
  - pymdownx.tasklist:
      custom_checkbox: true
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.superfences
  - pymdownx.highlight
  - def_list


nav:
  - Home: index.md
  - CS_BASIC: 
    - Overview: cs_basic/index.md
    - Shell: cs_basic/shell.md
    - Shell Tools and Scripting: cs_basic/Shell_Tools_and_Scripting.md
    - Editors:vim: cs_basic/Editors_vim.md
    - Data Wrangling: cs_basic/Data_Wrangling.md
    - Command Line Environment: cs_basic/Command-line-Environment.md
    - Version Control and Git: cs_basic/Version_Control.md
    - Debugging and Profiling: cs_basic/Debugging_and_Profiling.md
    - Metaprogramming: cs_basic/Metaprogramming.md
    - Security and Cryptography: cs_basic/Security_and_Cryptography.md
    - Others: cs_basic/Others.md
  - CPP_ADVANCE:
    - Overview: cpp_advance/index.md
    - Types and Structs: cpp_advance/Types_and_Structs.md
    - Initialization and References: cpp_advance/Initialization_and_References.md
    - Streams: cpp_advance/Streams.md
    - Containers: cpp_advance/Containers.md
    - Iterators and Pointers: cpp_advance/Iterators_and_Pointers.md
    - Classes: cpp_advance/Classes.md
    - Template Classes and Const Correctness: cpp_advance/Template_Classes_and_Const_Correctness.md
    - Template Functions: cpp_advance/Template_Functions.md
    - Functions and Lambdas: cpp_advance/Functions_and_Lambdas.md
    - Special Member Functions: cpp_advance/Special_Member_Functions.md
    - Move Semantics: cpp_advance/Move_Semantics.md
    - std::optional and Type Safety: cpp_advance/Optional_and_Type_Safety.md
    - RAII, Smart Pointers, and Building C++ Projects: cpp_advance/RAll_Smart_Pointers_and_Building_Cpp_Projects.md
  - QUADROTOR_BASIC: 
    - Overview: quadrotor_basic/index.md
  - FPGA: 
    - Overview: fpga/index.md
    - Something about FPGA: fpga/something_about_fpga.md
  - WIRELESS_COMMUNICATION: 
    - Overview: wireless_communication/index.md

extra:
  generator: false
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/LinHuangnan/something
      name: From that day on, if I was going somewhere, I was running.
      
copyright: Copyright &copy; 2020 - 2024 huangnan.lin

plugins:
  - search
  - git-authors
