site_name: huangnan.lin DevZone
theme:
  name: material
  custom_dir: custom_theme
  features: 
    - navigation.instant
    - navigation.tabs
    - navigation.indexes
    - navigation.tabs.sticky
    - navigation.sections
    - header.autohide
  
markdown_extensions:
  - toc:
      permalink: true
      toc_depth: "2-4"
      slugify: !!python/name:pymdownx.slugs.uslugify
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.arithmatex:
      generic: true
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.superfences
  - pymdownx.highlight
  - def_list



nav:
  - Home: index.md
  - CS_BASIC: 
    - Overview: cs_basic/index.md
    - Shell: cs_basic/shell.md
    - Shell Tools and Scripting: cs_basic/Shell_Tools_and_Scripting.md
    - Editors:vim: cs_basic/Editors_vim.md
    - Data Wrangling: cs_basic/Data_Wrangling.md
    - Command Line Environment: cs_basic/Command-line-Environment.md
    - Version Control and Git: cs_basic/Version_Control.md
    - Git Branch: cs_basic/git_branch.md
    - Debugging and Profiling: cs_basic/Debugging_and_Profiling.md
    - Metaprogramming: cs_basic/Metaprogramming.md
    - Security and Cryptography: cs_basic/Security_and_Cryptography.md
    - Others: cs_basic/Others.md
  - CPP_ADVANCE:
    - Overview: cpp_advance/index.md
    - Types and Structs: cpp_advance/Types_and_Structs.md
    - Initialization and References: cpp_advance/Initialization_and_References.md
    - Streams: cpp_advance/Streams.md
    - Containers: cpp_advance/Containers.md
    - Iterators and Pointers: cpp_advance/Iterators_and_Pointers.md
    - Classes: cpp_advance/Classes.md
    - Template Classes and Const Correctness: cpp_advance/Template_Classes_and_Const_Correctness.md
    - Template Functions: cpp_advance/Template_Functions.md
    - Functions and Lambdas: cpp_advance/Functions_and_Lambdas.md
    - Special Member Functions: cpp_advance/Special_Member_Functions.md
    - Move Semantics: cpp_advance/Move_Semantics.md
    - std::optional and Type Safety: cpp_advance/Optional_and_Type_Safety.md
    - RAII, Smart Pointers, and Building C++ Projects: cpp_advance/RAll_Smart_Pointers_and_Building_Cpp_Projects.md
  - QUADROTOR_BASIC: 
    - Overview: quadrotor_basic/index.md
  - FPGA: 
    - Overview: fpga/index.md
    - 深入理解FPGA结构: fpga/something_about_fpga.md
    - 数字芯片设计---握手与反压: fpga/handshake.md
    - Clock Domain Crossing(1) 亚稳态: fpga/cdc1.md
    - Clock Domain Crossing(2) 打两拍: fpga/cdc2.md
    - Clock Domain Crossing(3) 寄存器处理输出端口: fpga/cdc3.md
    - Clock Domain Crossing(4) 快时钟到慢时钟数据传输: fpga/cdc4.md
    - Clock Domain Crossing(5) 多信号跨时钟域传输: fpga/cdc5.md
  - WIRELESS_COMMUNICATION: 
    - Overview: wireless_communication/index.md
  - HANDSHAKE_PROTOCOL:
    - Overview: handshake_protocol/index.md
    - valid-ready握手协议的介绍与时序说明: handshake_protocol/h1.md
    - valid-ready接口与enable-xoff/bp接口的对比: handshake_protocol/h2.md
    - 握手协议中常用的并发断言介绍: handshake_protocol/h3.md
    - valid时序优化即forward打拍介绍: handshake_protocol/h4.md
    - ready时序优化即backward打拍介绍: handshake_protocol/h5.md
    - 同步fifo的握手协议适配: handshake_protocol/h6.md
    - 双向时序优化即forward-backward打拍的两种方式介绍: handshake_protocol/h7.md
    - 多路握手协议的融合场景与RTL编写: handshake_protocol/h8.md
    - 多路握手协议的拆分场景与RTL编写: handshake_protocol/h9.md
    - 应用于握手型接口的agent自动生成工具: handshake_protocol/h10.md

extra:
  generator: false
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/LinHuangnan/something
      name: From that day on, if I was going somewhere, I was running.
      
copyright: Copyright &copy; 2020 - 2024 huangnan.lin

plugins:
  - search
  - git-authors

extra_javascript:
  - javascripts/config.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
