site_name: huangnan.lin DevZone
theme:
  name: material
  custom_dir: custom_theme
  features: 
    - navigation.instant
    - navigation.tabs
    - navigation.indexes
    - navigation.tabs.sticky
    - navigation.sections
    - header.autohide
  
markdown_extensions:
  - toc:
      permalink: true
      toc_depth: "2-4"
      slugify: !!python/name:pymdownx.slugs.uslugify
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.arithmatex:
      generic: true
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.superfences
  - pymdownx.highlight
  - def_list



nav:
  - Home: index.md
  - CS_BASIC: 
    - Overview: cs_basic/index.md
    - Shell: cs_basic/shell.md
    - Shell Tools and Scripting: cs_basic/Shell_Tools_and_Scripting.md
    - Editors:vim: cs_basic/Editors_vim.md
    - Data Wrangling: cs_basic/Data_Wrangling.md
    - Command Line Environment: cs_basic/Command-line-Environment.md
    - Version Control and Git: cs_basic/Version_Control.md
    - Git Branch: cs_basic/git_branch.md  
    - Git Rebase: cs_basic/git_rebase.md
    - Debugging and Profiling: cs_basic/Debugging_and_Profiling.md
    - Metaprogramming: cs_basic/Metaprogramming.md
    - Security and Cryptography: cs_basic/Security_and_Cryptography.md
    - Others: cs_basic/Others.md
  - CPP_ADVANCE:
    - Overview: cpp_advance/index.md
    - Types and Structs: cpp_advance/Types_and_Structs.md
    - Initialization and References: cpp_advance/Initialization_and_References.md
    - Streams: cpp_advance/Streams.md
    - Containers: cpp_advance/Containers.md
    - Iterators and Pointers: cpp_advance/Iterators_and_Pointers.md
    - Classes: cpp_advance/Classes.md
    - Template Classes and Const Correctness: cpp_advance/Template_Classes_and_Const_Correctness.md
    - Template Functions: cpp_advance/Template_Functions.md
    - Functions and Lambdas: cpp_advance/Functions_and_Lambdas.md
    - Special Member Functions: cpp_advance/Special_Member_Functions.md
    - Move Semantics: cpp_advance/Move_Semantics.md
    - std::optional and Type Safety: cpp_advance/Optional_and_Type_Safety.md
    - RAII, Smart Pointers, and Building C++ Projects: cpp_advance/RAll_Smart_Pointers_and_Building_Cpp_Projects.md
  - QUADROTOR_BASIC: 
    - Overview: quadrotor_basic/index.md
  - FPGA: 
    - Overview: fpga/index.md
    - 深入理解FPGA结构: fpga/something_about_fpga.md
    - 数字芯片设计---握手与反压: fpga/handshake.md
    - FPGA设计的“打拍(寄存)”和“亚稳态”: fpga/pipelining.md
    - Clock Domain Crossing(1) 亚稳态: fpga/cdc1.md
    - Clock Domain Crossing(2) 打两拍: fpga/cdc2.md
    - Clock Domain Crossing(3) 寄存器处理输出端口: fpga/cdc3.md
    - Clock Domain Crossing(4) 快时钟到慢时钟数据传输: fpga/cdc4.md
    - Clock Domain Crossing(5) 多信号跨时钟域传输: fpga/cdc5.md
    - 单端口和双端口RAM: fpga/ram.md
    - 脉动阵列: fpga/pe.md
  - WIRELESS_COMMUNICATION: 
    - Overview: wireless_communication/index.md
  - HANDSHAKE_PROTOCOL:
    - Overview: handshake_protocol/index.md
    - valid-ready握手协议的介绍与时序说明: handshake_protocol/h1.md
    - valid-ready接口与enable-xoff/bp接口的对比: handshake_protocol/h2.md
    - 握手协议中常用的并发断言介绍: handshake_protocol/h3.md
    - valid时序优化即forward打拍介绍: handshake_protocol/h4.md
    - ready时序优化即backward打拍介绍: handshake_protocol/h5.md
    - 同步fifo的握手协议适配: handshake_protocol/h6.md
    - 双向时序优化即forward-backward打拍的两种方式介绍: handshake_protocol/h7.md
    - 多路握手协议的融合场景与RTL编写: handshake_protocol/h8.md
    - 多路握手协议的拆分场景与RTL编写: handshake_protocol/h9.md
    - 应用于握手型接口的agent自动生成工具: handshake_protocol/h10.md
  - LEARN_INTEL_FPGA:
    - Overview: learn_intel_fpga/index.md
    - Testbench文件的书写: learn_intel_fpga/testbench.md
    - Modelsim手动仿真: learn_intel_fpga/modelsim1.md
    - Modelsim联合仿真: learn_intel_fpga/modelsim2.md
  - SD_CARD_READER(VERILOG):
    - Overview: fpga_sd_card_reader/index.md
    - SD卡简介: fpga_sd_card_reader/sd1.md
    - SD卡常用命令: fpga_sd_card_reader/sd2.md
    - SPI接口与时序: fpga_sd_card_reader/sd3.md
    - SD卡的操作时序: fpga_sd_card_reader/sd4.md
    - SD读写测试实验模块框图: fpga_sd_card_reader/sd5.md
    - SD卡控制顶层模块RTL代码(sd_ctrl_top.v): fpga_sd_card_reader/sd6.md
    - SD卡控制器模块RTL代码(sd_init.v、sd_read.v、sd_write.v): fpga_sd_card_reader/sd7.md
  - VIVADO:
    - Overview: vivado/index.md
    - Vivado设计流程及使用模式: vivado/vivado1.md
    - 如何在设计中使用IP: vivado/vivado2.md
    - 基于XSim的逻辑仿真: vivado/vivado3.md
    - 基于ModelSim的逻辑仿真: vivado/vivado4.md
  - HLS:
    - Overview: hls/index.md
    - 软件工程师应该如何理解FPGA架构: hls/hls1.md
    - HLS工作机制: hls/hls2.md
    - Vivado HLS设计流程介绍: hls/hls3.md
    - Vivado HLS设计流程Demo: hls/hls4.md
    - 如何处理任意精度的数据类型: hls/hls5.md
    - 数据类型的转换: hls/hls6.md
    - 了解HLS中的复合数据类型: hls/hls7.md
    - Vivado HLS中的C++基本运算1: hls/hls8.md
    - Vivado HLS中的C++基本运算2: hls/hls9.md
    - 描述高效的C测试平台-测试激励: hls/hls10.md
    - 描述高效的C测试平台-输出监测与格式控制: hls/hls11.md
    - 接口综合-基本介绍: hls/hls12.md
    - 接口综合-对数组的处理: hls/hls13.md
    - 接口综合-demo: hls/hls14.md
    - for循环优化-基本性能指标: hls/hls15.md
    - for循环优化-循环合并: hls/hls16.md
    - for循环优化-数据流: hls/hls17.md
    - for循环优化-嵌套的for循环: hls/hls18.md
    - for循环优化-其它优化方法: hls/hls19.md
    - 数组优化-数组分割: hls/hls20.md
    - 数组优化-数组映射与重组: hls/hls21.md
    - 数组优化-其它优化方法: hls/hls22.md
    - Vivado HLS函数层面的优化: hls/hls23.md
    - Demo: hls/hls24.md
    - 总结: hls/hls25.md
    
  - SOC_DESIGN:
    - Overview: soc_design/index.md

  - PIM:
    - Overview: processing_in_memory/index.md
    - 存内计算综述(A_Modern_Primer_on_Processing_in_Memory): processing_in_memory/A_Modern_Primer_on_Processing_in_Memory.md

  - IC_INTERVIEW:
    - Overview: digital_ic_interview/index.md
    - FIFO深度计算: digital_ic_interview/01_fifo/fifo_depth.md
    - 同步FIFO: digital_ic_interview/01_fifo/sync_fifo.md
    - 异步FIFO: digital_ic_interview/01_fifo/async_fifo.md
    - 竞争冒险: digital_ic_interview/02_RaceCondition_Metastability_Synchronization/race_condition.md
    - 亚稳态: digital_ic_interview/02_RaceCondition_Metastability_Synchronization/metastability.md
    - 复位相关: digital_ic_interview/02_RaceCondition_Metastability_Synchronization/reset.md
    - 跨时钟域: digital_ic_interview/02_RaceCondition_Metastability_Synchronization/crc.md
    - 数字IC设计流程: digital_ic_interview/03_Design_Flow/flow_and_tools.md
    - FPGA原型验证: digital_ic_interview/03_Design_Flow/FPGA_prototyping.md
    - CDC跨时钟域处理: digital_ic_interview/04_STA_Timing_Constraints/cdc.md
    - AXI4总线介绍: digital_ic_interview/05_AXI/intro.md


    


extra:
  generator: false
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/LinHuangnan/something
      name: From that day on, if I was going somewhere, I was running.
      
copyright: Copyright &copy; 2020 - 2024 huangnan.lin

plugins:
  - search
  - git-authors

extra_javascript:
  - javascripts/config.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
